version: '2.1'
services:
  web:
    #build: ./web
    image: "phpcensor/php-censor-web:1.0-latest"
    ports:
    - "80:80"
    env_file:
    - ./env/phpcensor.env
    volumes:
    - ./artifacts:/var/www/html/public/artifacts
  worker:
    #build: ./worker
    image: "phpcensor/php-censor-worker:1.0-latest"
    env_file:
    - ./env/phpcensor.env
    volumes:
    - ./artifacts:/var/www/html/public/artifacts
  db:
    image: "postgres"
    user: postgres
    env_file:
    - ./env/database.pgsql.env
  queue:
    image: "schickling/beanstalkd"
    networks:
      default:
        aliases:
        - beanstalk
